export const expenses = {
  "date": "2025-12-15",
    expenses:[
        {
            "id":1,
            "TransactionType":"Expense",
            "amount":"400",
            "for":"Lunch",
        },
             {
            "id":2,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"bought Mouse",
        },
             {
            "id":3,
            "TransactionType":"Expense",
            "amount":"60",
            "for":"Pool",
        },
             {
            "id":4,
            "TransactionType":"Income",
            "amount":"800",
            "from":"Parents",
        },
             {
            "id":5,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"Break fast",
        },
             {
            "id":6,
            "TransactionType":"Income",
            "amount":"400",
            "from":"Ziidi",
        },
             {
            "id":7,
            "TransactionType":"Expense",
            "amount":"20",
            "for":"Coffee",
        },
         {
            "id":8,
            "TransactionType":"Expense",
            "amount":"400",
            "for":"Lunch",
        },
             {
            "id":9,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"bought House",
        },
             {
            "id":10,
            "TransactionType":"Expense",
            "amount":"60",
            "for":"Pool",
        },
             {
            "id":11,
            "TransactionType":"Income",
            "amount":"800",
            "from":"Parents",
        },
             {
            "id":12,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"Supper",
        },
             {
            "id":13,
            "TransactionType":"Income",
            "amount":"400",
            "from":"Ziidi",
        },
             {
            "id":14,
            "TransactionType":"Expense",
            "amount":"20",
            "for":"Coffee",
        },
         {
            "id":15,
            "TransactionType":"Expense",
            "amount":"400",
            "for":"Lunch",
        },
             {
            "id":16,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"bought Mouse",
        },
             {
            "id":17,
            "TransactionType":"Expense",
            "amount":"60",
            "for":"Pool",
        },
             {
            "id":18,
            "TransactionType":"Income",
            "amount":"800",
            "from":"Parents",
        },
             {
            "id":19,
            "TransactionType":"Expense",
            "amount":"900",
            "for":"Break fast",
        },
             {
            "id":20,
            "TransactionType":"Income",
            "amount":"400",
            "from":"Ziidi",
        },
             {
            "id":21,
            "TransactionType":"Expense",
            "amount":"20",
            "for":"Bundles",
        },

    ]
}